name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23' # Specify your Node.js version

      - name: Cache dependencies and Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-yarn-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
          MONGODB_URI: mongodb+srv://eldar:XDLJjap3xwZQIwRO@dreamcatcher.ohfafi.mongodb.net/?retryWrites=true&w=majority&appName=Dreamcatcher


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
            --load \
            --build-arg NODE_ENV=production \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -t dreamcatcher .

      - name: Push to Google Container Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcloud-key.json
          gcloud auth configure-docker
          docker tag dreamcatcher gcr.io/${{ secrets.GCP_PROJECT_ID }}/dreamcatcher
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dreamcatcher

    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcloud-key.json
          gcloud auth configure-docker
      - name: Deploy to Google Cloud Run
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy dreamcatcher \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dreamcatcher \
            --platform managed \
            --region ${{ vars.REGION }} \
            --cpu 8 \
            --memory 16Gi \
            --port ${{ vars.PORT }}
